version: '3.8'

services:
  trading-system:
    build: .
    container_name: trading-system
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET_KEY=${BINANCE_SECRET_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./trading_data.db:/app/trading_data.db
      - ./trading_bot.log:/app/trading_bot.log
    networks:
      - trading-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Resource limits for Oracle Cloud free tier
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # Optional Redis for caching (if needed)
  redis:
    image: redis:7-alpine
    container_name: trading-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-network
    # Resource limits for Oracle Cloud free tier
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.1'

networks:
  trading-network:
    driver: bridge

volumes:
  redis-data:
    driver: local